apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    purpose: jenkins-shared-deployement  
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/d/nick/kubernetes/jenkins/data/"



