apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
spec:
  storageClassName: local-storage  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  selector:     
    matchLabels:
      purpose: jenkins-shared-deployement