apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"    
spec:  
  rules:
  - host: super-web.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
