apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres2020
 #pg-db-password: postgres2020